### ISSUE TITLE
Switch repo to public

### ISSUE THREAD

**Issue by maoo** [finos/datahub#2]
Missing tasks, to be performed by @maoo and @grovesy on a call:
- [x] Review website contents
- [x] create branch structure (ie `dev` branch) - using https://github.com/probot/settings
- [x] Review latest code version (WIP)
- [x] Initial Roadmap declared in markdown
- [x] Initial Roadmap declared in Issues + Kanban board
- [x] Internal Citi review ("Citi 2020" the right copyright?)
- [x] Paul signs the first push (history override)
- [x] Switch repository to public
- [x] Test [datahub.finos.org](datahub.finos.org)
- [x] Update FINOS metadata
- [x] Set DataHub project kanban to public - https://github.com/orgs/finos/projects/12

**Comment by maoo** [comment]
All done here! In order to complete contribution process, we suggest to send out an annoucement to FINOS community, see https://finosfoundation.atlassian.net/browse/CONTRIB-55 . Thanks!

**Comment by mcleo-d** [comment]
Congratulations @grovesy for contributing Synthetic DataHub to FINOS. I'll reach out to you regarding the announce email shortly 🕺💃 🎸🎵🎶🎶
