### ISSUE TITLE
DataHub provides test and learn support to UBS innovation lab

### ISSUE THREAD

**Issue by mcleo-d** [finos/datahub#27]
### Description

This issue has been created to help support and guide UBS in the **Installation**, **Running** and **Modelling** of test data to inform UBS feedback and next steps into the DataHub project team.

### Success Criteria

- [x] UBS can `Clone`, `Build` and `Run` DataHub on a local machine. 
- [x] UBS have modelled test data that represents a small scale internal test scenario.
- [x] UBS have provided feedback and next steps to the DataHub project team.

### Definition of Done

UBS have enough information to make an informed choice on moving forward with DataHub and have provided collaboration requirements to the DataHub project team whilst agreeing next steps.

**Comment by mcleo-d** [comment]
@grovesy - Just letting you know Kimmy is on annual leave and I'll be arranging an update session upon her return 👍

**Comment by grovesy** [comment]
Great - I've started work on ISDA common-data-model examples which should take us through some examples of creating entities like accounts, trades, etc

**Comment by mcleo-d** [comment]
The following is a project update summary between @kimmyyoo, @grovesy and @andrewcarrblue.

* @kimmyyoo's synthetic data requirements aren't necessarily solved by a single tool in the marketplace. This includes DataHub.
* Investigations still ongoing to find relevant tools, including taking development in house.
* @kimmyyoo introduced to https://github.com/finos/datahub/issues/30#issuecomment-651734549 by @andrewcarrblue.
* @kimmyyoo to investigate team requirements for adding synthetic data requirements to DataHub and DataHelix backlogs.
* @kimmyyoo invited to join DataHub and DataHelix project calls and agreed a monthly cadence, with additional meetings where needed.
* @kimmyyoo to investigate additional team members to join who are close to project requirements and who can help groom ongoing synthetic data stories.
